
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // CLI operations (migrate/dev/deploy/push/studio) must bypass the
    // transaction-mode pooler in DATABASE_URL, otherwise DDL hangs.
    url: env("DIRECT_URL"),
  },
});
