import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import { createHash } from "crypto";
import { Writable } from "stream";
import { formatMinorUnits } from "../utils/documentCurrency";
import { A4, PDF_COLORS, PDF_CONTENT_WIDTH, PDF_MARGIN, formatTimestamp, resolveTimezone } from "./pdfReportRenderer";
import { fetchLogoBuffer, formatContactLine, type OrgBranding } from "./orgBrandingService";

/**
 * Building blocks shared by the one-page documents (e-receipts and payment
 * vouchers). They deliberately mirror the report renderer so a receipt and a
 * balance sheet printed from the same organization are recognisably the same
 * product.
 */

export const DOC_COLORS = PDF_COLORS;

export const DOC_WIDTH = A4.width;
export const DOC_HEIGHT = A4.height;
export const DOC_MARGIN = PDF_MARGIN;
export const DOC_CONTENT_WIDTH = PDF_CONTENT_WIDTH;

export const FONT_REGULAR = "Helvetica";
export const FONT_BOLD = "Helvetica-Bold";
export const FONT_ITALIC = "Helvetica-Oblique";
export const FONT_MONO = "Courier";

export const FOOTER_DISCLAIMER = "Generated by Church Financier — Executive Financial Suite";

export function money(minor: bigint | number | string, currency: string): string {
  return formatMinorUnits(minor, currency);
}

/**
 * A short, stable verification fingerprint for a document.
 *
 * This is a tamper-evident digest, not a signature: it lets a donor confirm
 * the printed figure matches the stored record, and it is what the QR code
 * encodes so a scanner lands on a checkable value.
 */
export function verificationHash(parts: Array<string | null | undefined>): string {
  return createHash("sha256")
    .update(parts.map((part) => (part ?? "").trim()).join("|"), "utf8")
    .digest("hex")
    .toUpperCase();
}

/** Group the hash into 4-char blocks so it is readable when printed. */
export function formatHash(hash: string): string {
  return hash.match(/.{1,4}/g)?.join(" ") ?? hash;
}

export interface QrPayload {
  reference: string;
  amount: bigint | number | string;
  currency: string;
  date: Date;
  hash: string;
}

/** Render the verification payload as a compact single-line text block. */
export function verificationPayload(payload: QrPayload): string {
  const amount = money(payload.amount, payload.currency);
  return [
    "CHURCH FINANCIER PAYMENT VERIFICATION",
    `REF:${payload.reference}`,
    `AMOUNT:${amount}`,
    `DATE:${payload.date.toISOString()}`,
    `HASH:${payload.hash}`,
  ].join("\n");
}

/**
 * Draw a QR code (or a labelled placeholder when the code cannot be built).
 * Returns the width actually used so callers can centre it.
 */
export async function drawQrCode(
  doc: PDFKit.PDFDocument,
  text: string,
  options: { x: number; y: number; size: number; fallbackColor?: string }
): Promise<void> {
  const { x, y, size } = options;
  try {
    const png = await QRCode.toBuffer(text, {
      type: "png",
      errorCorrectionLevel: "M",
      margin: 1,
      width: Math.round(size * 4),
      color: { dark: "#1E293B", light: "#FFFFFF" },
    });
    doc.image(png, x, y, { fit: [size, size] });
  } catch {
    // A missing QR is a cosmetic gap, not a reason to fail the document.
    doc
      .save()
      .rect(x, y, size, size)
      .lineWidth(0.5)
      .stroke(DOC_COLORS.border)
      .restore();
    doc
      .font(FONT_REGULAR)
      .fontSize(5.5)
      .fillColor(DOC_COLORS.muted)
      .text("VERIFICATION", x, y + size / 2 - 4, { width: size, align: "center" });
  }
}

/** Filled rectangle helper that does not leak path state. */
export function drawFill(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  width: number,
  height: number,
  color: string
): void {
  doc.save();
  doc.rect(x, y, width, height).fill(color);
  doc.restore();
}

export function drawRoundedFill(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number,
  color: string
): void {
  doc.save();
  doc.roundedRect(x, y, width, height, radius).fill(color);
  doc.restore();
}

/**
 * Organization header for a single-page document: logo (or monogram),
 * organization name, contact line, and the document title on the right.
 */
export async function drawDocumentHeader(
  doc: PDFKit.PDFDocument,
  branding: OrgBranding,
  options: { title: string; reference: string; y?: number; height?: number }
): Promise<number> {
  const y = options.y ?? DOC_MARGIN;
  const height = options.height ?? 74;
  const logoSize = height - 22;
  const textX = DOC_MARGIN + logoSize + 26;
  const textWidth = DOC_CONTENT_WIDTH - (textX - DOC_MARGIN) - 150;

  drawRoundedFill(doc, DOC_MARGIN, y, DOC_CONTENT_WIDTH, height, 6, DOC_COLORS.primary);

  const logo = await fetchLogoBuffer(branding.logoUrl);
  if (logo) {
    try {
      doc.image(logo.buffer, DOC_MARGIN + 11, y + 11, { fit: [logoSize, logoSize] });
    } catch {
      drawMonogramBadge(doc, DOC_MARGIN + 11, y + 11, logoSize, branding.name);
    }
  } else {
    drawMonogramBadge(doc, DOC_MARGIN + 11, y + 11, logoSize, branding.name);
  }

  doc
    .font(FONT_BOLD)
    .fontSize(13)
    .fillColor(DOC_COLORS.white)
    .text(branding.name.toUpperCase(), textX, y + 13, { width: textWidth, ellipsis: true });

  doc
    .font(FONT_BOLD)
    .fontSize(9)
    .fillColor(DOC_COLORS.white)
    .text(options.title.toUpperCase(), textX, y + 31, { width: textWidth, ellipsis: true });

  const contact = formatContactLine(branding);
  if (contact) {
    doc
      .font(FONT_REGULAR)
      .fontSize(6.8)
      .fillColor(DOC_COLORS.white)
      .text(contact, textX, y + 47, { width: textWidth, ellipsis: true });
  }

  // Document reference, right aligned inside the header band.
  doc.font(FONT_REGULAR).fontSize(6.5).fillColor(DOC_COLORS.white);
  doc.text(options.reference, DOC_MARGIN + DOC_CONTENT_WIDTH - 150, y + 24, {
    width: 138,
    align: "right",
    ellipsis: true,
  });
  doc.font(FONT_BOLD).fontSize(7.5);
  doc.text("Official document", DOC_MARGIN + DOC_CONTENT_WIDTH - 150, y + 38, {
    width: 138,
    align: "right",
  });

  return y + height;
}

/** Light monogram panel used when no logo image is configured. */
function drawMonogramBadge(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  size: number,
  name: string
): void {
  drawRoundedFill(doc, x, y, size, size, 4, DOC_COLORS.white);
  doc
    .font(FONT_BOLD)
    .fontSize(size * 0.46)
    .fillColor(DOC_COLORS.primary)
    .text(name.trim().charAt(0).toUpperCase() || "?", x, y + size * 0.24, {
      width: size,
      align: "center",
    });
}

export interface MetadataItem {
  label: string;
  value: string;
  tone?: "default" | "success" | "warning" | "danger";
}

/**
 * The metadata bar: a light panel divided into labelled cells. This is where
 * the reference number, timestamp, method and status live.
 */
export function drawMetadataBar(
  doc: PDFKit.PDFDocument,
  items: MetadataItem[],
  options: { y: number; height?: number }
): number {
  const height = options.height ?? 46;
  const y = options.y;
  const cellWidth = DOC_CONTENT_WIDTH / items.length;

  drawRoundedFill(doc, DOC_MARGIN, y, DOC_CONTENT_WIDTH, height, 4, DOC_COLORS.stripe);
  doc.save();
  doc
    .roundedRect(DOC_MARGIN, y, DOC_CONTENT_WIDTH, height, 4)
    .lineWidth(0.5)
    .stroke(DOC_COLORS.border);
  doc.restore();

  items.forEach((item, index) => {
    const x = DOC_MARGIN + index * cellWidth;
    if (index > 0) {
      doc.save();
      doc
        .moveTo(x, y + 8)
        .lineTo(x, y + height - 8)
        .lineWidth(0.5)
        .stroke(DOC_COLORS.border);
      doc.restore();
    }
    const toneColor = toneColorFor(item.tone);
    doc
      .font(FONT_REGULAR)
      .fontSize(6.2)
      .fillColor(DOC_COLORS.muted)
      .text(item.label.toUpperCase(), x + 6, y + 10, { width: cellWidth - 12, align: "center" });
    doc
      .font(FONT_BOLD)
      .fontSize(item.value.length > 18 ? 7 : 8.5)
      .fillColor(toneColor)
      .text(item.value, x + 6, y + 23, { width: cellWidth - 12, align: "center", ellipsis: true });
  });

  return y + height;
}

function toneColorFor(tone: MetadataItem["tone"]): string {
  if (tone === "success") return DOC_COLORS.success;
  if (tone === "warning") return DOC_COLORS.warning;
  if (tone === "danger") return DOC_COLORS.danger;
  return DOC_COLORS.secondary;
}

/** A pill-shaped status badge, e.g. APPROVED / PAID / PENDING. */
export function drawStatusBadge(
  doc: PDFKit.PDFDocument,
  status: string,
  options: { x: number; y: number; width?: number; height?: number }
): void {
  const width = options.width ?? 96;
  const height = options.height ?? 24;
  const color = statusColorFor(status);
  drawRoundedFill(doc, options.x, options.y, width, height, 3, color);
  doc
    .font(FONT_BOLD)
    .fontSize(8)
    .fillColor(DOC_COLORS.white)
    .text(status.toUpperCase(), options.x, options.y + height / 2 - 4.5, {
      width,
      align: "center",
      ellipsis: true,
    });
}

export function statusColorFor(status: string): string {
  const upper = status.toUpperCase();
  if (upper === "APPROVED" || upper === "PAID" || upper === "COMPLETED") return DOC_COLORS.success;
  if (upper === "PENDING" || upper === "FIRST_APPROVED" || upper === "SUBMITTED") return DOC_COLORS.warning;
  if (upper === "REJECTED" || upper === "CANCELLED" || upper === "OUT OF BALANCE") return DOC_COLORS.danger;
  return DOC_COLORS.muted;
}

/** Prominent "total paid" banner. */
export function drawTotalBanner(
  doc: PDFKit.PDFDocument,
  options: {
    y: number;
    label: string;
    amount: string;
    note?: string;
    height?: number;
  }
): number {
  const height = options.height ?? 66;
  drawRoundedFill(doc, DOC_MARGIN, options.y, DOC_CONTENT_WIDTH, height, 4, DOC_COLORS.stripe);
  doc.save();
  doc
    .roundedRect(DOC_MARGIN, options.y, DOC_CONTENT_WIDTH, height, 4)
    .lineWidth(0.5)
    .stroke(DOC_COLORS.border);
  doc.restore();

  doc
    .font(FONT_BOLD)
    .fontSize(7.5)
    .fillColor(DOC_COLORS.muted)
    .text(options.label.toUpperCase(), DOC_MARGIN, options.y + 10, {
      width: DOC_CONTENT_WIDTH,
      align: "center",
    });
  doc
    .font(FONT_BOLD)
    .fontSize(options.amount.length > 18 ? 20 : 24)
    .fillColor(DOC_COLORS.primary)
    .text(options.amount, DOC_MARGIN, options.y + 24, { width: DOC_CONTENT_WIDTH, align: "center" });
  if (options.note) {
    doc
      .font(FONT_ITALIC)
      .fontSize(6.8)
      .fillColor(DOC_COLORS.muted)
      .text(options.note, DOC_MARGIN, options.y + height - 13, {
        width: DOC_CONTENT_WIDTH,
        align: "center",
        ellipsis: true,
      });
  }
  return options.y + height;
}

export interface TableColumn {
  header: string;
  flex: number;
  align?: "left" | "right" | "center";
  mono?: boolean;
}

export interface TableRow {
  cells: string[];
  kind?: "data" | "subtotal" | "total";
  /** Skip the stripe fill for this row. */
  plain?: boolean;
}

/** Widths that sum exactly to the content width. */
export function computeColumnWidths(columns: TableColumn[]): number[] {
  const total = columns.reduce((sum, column) => sum + column.flex, 0) || 1;
  const widths = columns.map((column) => Math.max(28, Math.floor((column.flex * DOC_CONTENT_WIDTH) / total)));
  const used = widths.reduce((sum, width) => sum + width, 0);
  const diff = Math.round(DOC_CONTENT_WIDTH - used);
  if (diff !== 0 && widths.length > 0) {
    let widest = 0;
    for (let i = 1; i < widths.length; i++) {
      if (widths[i] > widths[widest]) widest = i;
    }
    widths[widest] = Math.max(28, widths[widest] + diff);
  }
  return widths;
}

/**
 * A structured transaction table: navy header, striped rows, and an optional
 * emphasized total row. Returns the y coordinate below the table.
 */
export function drawTable(
  doc: PDFKit.PDFDocument,
  columns: TableColumn[],
  rows: TableRow[],
  options: { y: number; rowHeight?: number; headerHeight?: number; emptyMessage?: string }
): number {
  const widths = computeColumnWidths(columns);
  const headerHeight = options.headerHeight ?? 22;
  const rowHeight = options.rowHeight ?? 19;
  let y = options.y;

  drawFill(doc, DOC_MARGIN, y, DOC_CONTENT_WIDTH, headerHeight, DOC_COLORS.primary);
  let x = DOC_MARGIN;
  columns.forEach((column, index) => {
    doc
      .font(FONT_BOLD)
      .fontSize(6.8)
      .fillColor(DOC_COLORS.white)
      .text(column.header.toUpperCase(), x + 7, y + 7.5, {
        width: widths[index] - 14,
        align: column.align ?? "left",
        ellipsis: true,
        lineBreak: false,
      });
    x += widths[index];
  });
  y += headerHeight;

  if (rows.length === 0) {
    doc
      .font(FONT_REGULAR)
      .fontSize(8)
      .fillColor(DOC_COLORS.muted)
      .text(options.emptyMessage ?? "No line items recorded.", DOC_MARGIN + 8, y + 7, {
        width: DOC_CONTENT_WIDTH - 16,
      });
    y += rowHeight + 2;
    return y;
  }

  rows.forEach((row, index) => {
    const kind = row.kind ?? "data";
    if (kind === "total") {
      drawFill(doc, DOC_MARGIN, y, DOC_CONTENT_WIDTH, rowHeight, DOC_COLORS.primary);
    } else if (kind === "subtotal" || !row.plain) {
      if (kind === "subtotal" || index % 2 === 0) {
        drawFill(doc, DOC_MARGIN, y, DOC_CONTENT_WIDTH, rowHeight, DOC_COLORS.stripe);
      }
    }

    let cellX = DOC_MARGIN;
    columns.forEach((column, columnIndex) => {
      const isEmphasized = kind !== "data";
      doc
        .font(isEmphasized || column.mono ? FONT_BOLD : column.mono ? FONT_MONO : FONT_REGULAR)
        .fontSize(7.6)
        .fillColor(kind === "total" ? DOC_COLORS.white : DOC_COLORS.body)
        .text(row.cells[columnIndex] ?? "", cellX + 7, y + 6, {
          width: widths[columnIndex] - 14,
          align: column.align ?? "left",
          ellipsis: true,
          lineBreak: false,
        });
      cellX += widths[columnIndex];
    });

    y += rowHeight;
    doc.save();
    doc
      .moveTo(DOC_MARGIN, y)
      .lineTo(DOC_MARGIN + DOC_CONTENT_WIDTH, y)
      .lineWidth(0.25)
      .stroke(DOC_COLORS.border);
    doc.restore();
  });

  return y;
}

/**
 * Signature/audit footer: signature rules, a verification QR with its hash,
 * and the product disclaimer.
 */
export async function drawAuditFooter(
  doc: PDFKit.PDFDocument,
  options: {
    y: number;
    signatures: Array<{ role: string; hint?: string; name?: string }>;
    qrText: string;
    hash: string;
    printedAt: Date;
    timezone: string;
    note?: string;
  }
): Promise<void> {
  const sigColumnWidth = (DOC_CONTENT_WIDTH - 180) / 2;
  const sigY = options.y;

  const drawSignature = (x: number, entry: { role: string; hint?: string; name?: string }) => {
    doc
      .save()
      .moveTo(x, sigY + 30)
      .lineTo(x + sigColumnWidth, sigY + 30)
      .lineWidth(0.75)
      .stroke(DOC_COLORS.border);
    doc.restore();
    doc
      .font(FONT_BOLD)
      .fontSize(7.5)
      .fillColor(DOC_COLORS.secondary)
      .text(entry.role.toUpperCase(), x, sigY + 35, { width: sigColumnWidth, align: "center" });
    if (entry.hint) {
      doc
        .font(FONT_REGULAR)
        .fontSize(6.5)
        .fillColor(DOC_COLORS.muted)
        .text(entry.hint, x, sigY + 46, { width: sigColumnWidth, align: "center" });
    }
    if (entry.name) {
      doc
        .font(FONT_ITALIC)
        .fontSize(6.5)
        .fillColor(DOC_COLORS.muted)
        .text(entry.name, x, sigY + 56, { width: sigColumnWidth, align: "center" });
    }
  };

  drawSignature(DOC_MARGIN, options.signatures[0] ?? { role: "Authorized Signature" });
  drawSignature(DOC_MARGIN + sigColumnWidth + 16, options.signatures[1] ?? { role: "Recipient" });

  // Verification block, right aligned.
  const qrSize = 56;
  const qrX = DOC_MARGIN + DOC_CONTENT_WIDTH - qrSize;
  const qrY = sigY - 6;
  await drawQrCode(doc, options.qrText, { x: qrX, y: qrY, size: qrSize });
  doc
    .font(FONT_BOLD)
    .fontSize(6.2)
    .fillColor(DOC_COLORS.secondary)
    .text("SCAN TO VERIFY", qrX - 34, qrY + qrSize + 3, { width: qrSize + 34, align: "right" });
  doc
    .font(FONT_MONO)
    .fontSize(4.6)
    .fillColor(DOC_COLORS.muted)
    .text(formatHash(options.hash).slice(0, 44), qrX - 84, qrY + qrSize + 12, {
      width: qrSize + 84,
      align: "right",
      lineBreak: false,
    });

  if (options.note) {
    doc
      .font(FONT_REGULAR)
      .fontSize(6.5)
      .fillColor(DOC_COLORS.muted)
      .text(options.note, DOC_MARGIN, sigY + 68, {
        width: DOC_CONTENT_WIDTH - qrSize - 20,
      });
  }

  // Bottom disclaimer strip.
  const stripY = DOC_HEIGHT - DOC_MARGIN - 26;
  doc.save();
  doc
    .moveTo(DOC_MARGIN, stripY)
    .lineTo(DOC_MARGIN + DOC_CONTENT_WIDTH, stripY)
    .lineWidth(0.5)
    .stroke(DOC_COLORS.border);
  doc.restore();
  doc
    .font(FONT_REGULAR)
    .fontSize(6.4)
    .fillColor(DOC_COLORS.muted)
    .text(FOOTER_DISCLAIMER, DOC_MARGIN, stripY + 5, { width: DOC_CONTENT_WIDTH, align: "center" });
  doc.fontSize(5.8);
  doc.text(
    `Printed ${formatTimestamp(options.printedAt, resolveTimezone(options.timezone))} (${options.timezone}) · This document is valid without a wet signature when electronically verified.`,
    DOC_MARGIN,
    stripY + 14,
    { width: DOC_CONTENT_WIDTH, align: "center" }
  );
}

/** Convenience wrapper for a bordered key/value grid. */
export function drawDefinitionList(
  doc: PDFKit.PDFDocument,
  entries: Array<{ label: string; value: string; emphasis?: boolean }>,
  options: { y: number; labelFlex?: number; rowHeight?: number; stripe?: boolean }
): number {
  const labelFlex = options.labelFlex ?? 1.4;
  const valueFlex = 2;
  const labelWidth = Math.floor((labelFlex / (labelFlex + valueFlex)) * DOC_CONTENT_WIDTH);
  const valueWidth = DOC_CONTENT_WIDTH - labelWidth;
  const rowHeight = options.rowHeight ?? 20;
  let y = options.y;

  entries.forEach((entry, index) => {
    if (options.stripe && index % 2 === 0) {
      drawFill(doc, DOC_MARGIN, y, DOC_CONTENT_WIDTH, rowHeight, DOC_COLORS.stripe);
    }
    doc
      .font(FONT_REGULAR)
      .fontSize(6.8)
      .fillColor(DOC_COLORS.muted)
      .text(entry.label.toUpperCase(), DOC_MARGIN + 10, y + 7, { width: labelWidth - 16, ellipsis: true });
    doc
      .font(entry.emphasis ? FONT_BOLD : FONT_REGULAR)
      .fontSize(entry.emphasis ? 8.5 : 8)
      .fillColor(entry.emphasis ? DOC_COLORS.primary : DOC_COLORS.body)
      .text(entry.value || "—", DOC_MARGIN + labelWidth, y + 6, {
        width: valueWidth - 12,
        ellipsis: true,
      });
    y += rowHeight;
    doc.save();
    doc
      .moveTo(DOC_MARGIN, y)
      .lineTo(DOC_MARGIN + DOC_CONTENT_WIDTH, y)
      .lineWidth(0.25)
      .stroke(DOC_COLORS.border);
    doc.restore();
  });

  return y;
}

/** Create a one-page A4 document with the standard page box and margins. */
export function createDocument(title: string, branding: OrgBranding, subject: string): PDFKit.PDFDocument {
  return new PDFDocument({
    size: [DOC_WIDTH, DOC_HEIGHT],
    margin: DOC_MARGIN,
    bufferPages: true,
    info: {
      Title: `${title} — ${branding.name}`,
      Author: branding.name,
      Subject: subject,
      Creator: FOOTER_DISCLAIMER,
      Producer: "Church Financier",
    },
  });
}

/**
 * Finalize a document into a single Buffer.
 *
 * The document is buffered rather than piped: piping starts the stream flowing
 * immediately, so a listener attached afterwards would miss the leading bytes
 * (including the `%PDF-` header). Buffering also lets callers reuse the bytes
 * for audit trails or email attachments.
 */
export function collectDocument(doc: PDFKit.PDFDocument): Promise<Buffer> {
  const chunks: Buffer[] = [];
  return new Promise((resolve, reject) => {
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.once("end", () => resolve(Buffer.concat(chunks)));
    doc.once("error", reject);
    doc.end();
  });
}

/**
 * Finalize a document and deliver it to a response-like writable.
 *
 * Returns the same bytes that were written, so callers can assert on or
 * archive the rendered document.
 */
export async function deliverDocument(
  doc: PDFKit.PDFDocument,
  target: Writable
): Promise<Buffer> {
  const buffer = await collectDocument(doc);
  target.write(buffer);
  target.end();
  return buffer;
}
